# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=128)),
                ('significance', models.CharField(choices=[('ge', 'general'), ('in', 'important')], default='ge', max_length=9)),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
            ],
        ),
    ]
