# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_plans_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='significance',
            field=models.CharField(choices=[('ge', 'general'), ('im', 'important')], default='ge', max_length=9),
        ),
    ]
